#!/usr/bin/env python3

CONSTELLATIONS = {
    'And': {'name': 'Andromeda', 'genitive': 'Andromedae'},
    'Ant': {'name': 'Antlia', 'genitive': 'Antliae'},
    'Aps': {'name': 'Apus', 'genitive': 'Apodis'},
    'Aqr': {'name': 'Aquarius', 'genitive': 'Aquarii'},
    'Aql': {'name': 'Aquila', 'genitive': 'Aquilae'},
    'Ara': {'name': 'Ara', 'genitive': 'Arae'},
    'Ari': {'name': 'Aries', 'genitive': 'Arietis'},
    'Aur': {'name': 'Auriga', 'genitive': 'Aurigae'},
    'Boo': {'name': 'Boötes', 'genitive': 'Boötis'},
    'Cae': {'name': 'Caelum', 'genitive': 'Caeli'},
    'Cam': {'name': 'Camelopardalis', 'genitive': 'Camelopardalis'},
    'Cnc': {'name': 'Cancer', 'genitive': 'Cancri'},
    'CVn': {'name': 'Canes Venatici', 'genitive': 'Canum Venaticorum'},
    'CMa': {'name': 'Canis Major', 'genitive': 'Canis Majoris'},
    'CMi': {'name': 'Canis Minor', 'genitive': 'Canis Minoris'},
    'Cap': {'name': 'Capricornus', 'genitive': 'Capricorni'},
    'Car': {'name': 'Carina', 'genitive': 'Carinae'},
    'Cas': {'name': 'Cassiopeia', 'genitive': 'Cassiopeiae'},
    'Cen': {'name': 'Centaurus', 'genitive': 'Centauri'},
    'Cep': {'name': 'Cepheus', 'genitive': 'Cephei'},
    'Cet': {'name': 'Cetus', 'genitive': 'Ceti'},
    'Cha': {'name': 'Chamaeleon', 'genitive': 'Chamaeleontis'},
    'Cir': {'name': 'Circinus', 'genitive': 'Circini'},
    'Col': {'name': 'Columba', 'genitive': 'Columbae'},
    'Com': {'name': 'Coma Berenices', 'genitive': 'Comae Berenices'},
    'CrA': {'name': 'Corona Australis', 'genitive': 'Coronae Australis'},
    'CrB': {'name': 'Corona Borealis', 'genitive': 'Coronae Borealis'},
    'Crv': {'name': 'Corvus', 'genitive': 'Corvi'},
    'Crt': {'name': 'Crater', 'genitive': 'Crateris'},
    'Cru': {'name': 'Crux', 'genitive': 'Crucis'},
    'Cyg': {'name': 'Cygnus', 'genitive': 'Cygni'},
    'Del': {'name': 'Delphinus', 'genitive': 'Delphini'},
    'Dor': {'name': 'Dorado', 'genitive': 'Doradus'},
    'Dra': {'name': 'Draco', 'genitive': 'Draconis'},
    'Equ': {'name': 'Equuleus', 'genitive': 'Equulei'},
    'Eri': {'name': 'Eridanus', 'genitive': 'Eridani'},
    'For': {'name': 'Fornax', 'genitive': 'Fornacis'},
    'Gem': {'name': 'Gemini', 'genitive': 'Geminorum'},
    'Gru': {'name': 'Grus', 'genitive': 'Gruis'},
    'Her': {'name': 'Hercules', 'genitive': 'Herculis'},
    'Hor': {'name': 'Horologium', 'genitive': 'Horologii'},
    'Hya': {'name': 'Hydra', 'genitive': 'Hydrae'},
    'Hyi': {'name': 'Hydrus', 'genitive': 'Hydri'},
    'Ind': {'name': 'Indus', 'genitive': 'Indi'},
    'Lac': {'name': 'Lacerta', 'genitive': 'Lacertae'},
    'Leo': {'name': 'Leo', 'genitive': 'Leonis'},
    'LMi': {'name': 'Leo Minor', 'genitive': 'Leonis Minoris'},
    'Lep': {'name': 'Lepus', 'genitive': 'Leporis'},
    'Lib': {'name': 'Libra', 'genitive': 'Librae'},
    'Lup': {'name': 'Lupus', 'genitive': 'Lupi'},
    'Lyn': {'name': 'Lynx', 'genitive': 'Lyncis'},
    'Lyr': {'name': 'Lyra', 'genitive': 'Lyrae'},
    'Men': {'name': 'Mensa', 'genitive': 'Mensae'},
    'Mic': {'name': 'Microscopium', 'genitive': 'Microscopii'},
    'Mon': {'name': 'Monoceros', 'genitive': 'Monocerotis'},
    'Mus': {'name': 'Musca', 'genitive': 'Muscae'},
    'Nor': {'name': 'Norma', 'genitive': 'Normae'},
    'Oct': {'name': 'Octans', 'genitive': 'Octantis'},
    'Oph': {'name': 'Ophiuchus', 'genitive': 'Ophiuchi'},
    'Ori': {'name': 'Orion', 'genitive': 'Orionis'},
    'Pav': {'name': 'Pavo', 'genitive': 'Pavonis'},
    'Peg': {'name': 'Pegasus', 'genitive': 'Pegasi'},
    'Per': {'name': 'Perseus', 'genitive': 'Persei'},
    'Phe': {'name': 'Phoenix', 'genitive': 'Phoenicis'},
    'Pic': {'name': 'Pictor', 'genitive': 'Pictoris'},
    'Psc': {'name': 'Pisces', 'genitive': 'Piscium'},
    'PsA': {'name': 'Piscis Austrinus', 'genitive': 'Piscis Austrini'},
    'Pup': {'name': 'Puppis', 'genitive': 'Puppis'},
    'Pyx': {'name': 'Pyxis', 'genitive': 'Pyxidis'},
    'Ret': {'name': 'Reticulum', 'genitive': 'Reticuli'},
    'Sge': {'name': 'Sagitta', 'genitive': 'Sagittae'},
    'Sgr': {'name': 'Sagittarius', 'genitive': 'Sagittarii'},
    'Sco': {'name': 'Scorpius', 'genitive': 'Scorpii'},
    'Scl': {'name': 'Sculptor', 'genitive': 'Sculptoris'},
    'Sct': {'name': 'Scutum', 'genitive': 'Scuti'},
    'Ser': {'name': 'Serpens', 'genitive': 'Serpentis'},
    'Sex': {'name': 'Sextans', 'genitive': 'Sextantis'},
    'Tau': {'name': 'Taurus', 'genitive': 'Tauri'},
    'Tel': {'name': 'Telescopium', 'genitive': 'Telescopii'},
    'Tri': {'name': 'Triangulum', 'genitive': 'Trianguli'},
    'TrA': {'name': 'Triangulum Australe', 'genitive': 'Trianguli Australis'},
    'Tuc': {'name': 'Tucana', 'genitive': 'Tucanae'},
    'UMa': {'name': 'Ursa Major', 'genitive': 'Ursae Majoris'},
    'UMi': {'name': 'Ursa Minor', 'genitive': 'Ursae Minoris'},
    'Vel': {'name': 'Vela', 'genitive': 'Velorum'},
    'Vir': {'name': 'Virgo', 'genitive': 'Virginis'},
    'Vol': {'name': 'Volans', 'genitive': 'Volantis'},
    'Vul': {'name': 'Vulpecula', 'genitive': 'Vulpeculae'},
}


def name(id: str) -> str:
    return CONSTELLATIONS[id]['name']


def genitive(id: str) -> str:
    return CONSTELLATIONS[id]['genitive']
