[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "astro-gen"
dynamic = ["version"]
description = "Generator for astronomy observation pages"
readme = "README.md"
requires-python = ">=3.12"
license-files = ["LICENSE"]
authors = [
    {name = "Balazs Toth", email = "baltth@gmail.com"}
]

dependencies = [
    "setuptools",
    "natsort == 8.*",
    "numpy == 2.*",
    "pillow == 11.3.*",
    "PyYAML == 6.*",
    "python-slugify == 8.*",
    "requests == 2.*",
    "ruamel.yaml == 0.18.15",
]

[project.optional-dependencies]
dev = [
    "autopep8",
    "mypy",
    "pylint",
    "pytest",
    "pytest-mock",
    "pytest-cov",
]

[project.scripts]
astro-gen = "astro_gen.main:main"

[tool.setuptools]
packages = ["astro_gen"]

[tool.setuptools.dynamic]
version = {attr = "astro_gen.meta.git_describe_version"}

[tool.pytest.ini_options]
testpaths = ["tests"]
